config/routes.rb
Rails.application.routes.draw do
  # get 'tasks/index'

  # get 'tasks/new'

  # get 'tasks/create'

  # get 'tasks/show'

  # get 'tasks/edit'

  # get 'tasks/update'

  # get 'tasks/destroy'

  resources :tasks

  put 'tasks/:id/done', to: 'tasks#done', as: 'done_task'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :load_task, only: [:show, :update, :edit, :destroy, :done]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    Task.create(task_params)
    redirect_to tasks_path
  end

  def edit
  end

  def update
    @task.update_attributes(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  def done
    @task.update_attributes(done: true)
    redirect_to tasks_path
  end

  private

  def load_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:name, :content, :done)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Tasks#edit</h1>
<p>Find me in app/views/tasks/edit.html.erb</p>

<%= render 'form' %>

app/views/tasks/index.html.erb
<h1>Tasks#index</h1>
<p>Find me in app/views/tasks/index.html.erb</p>


<table>
  <tr>
    <th>Name</th>
    <th>Content</th>
    <th>Status</th>
    <th>Action</th>
  </tr>
  <% @tasks.each do |task| %>
  <tr>
    <td><%= link_to task.name, task_path(task) %></td>
    <td><%= task.content %></td>
    <td><% if task.done == true %>Done!<% else %>To do!<% end %></td>
    <td>
      <%= link_to "Delete", task_path(task),
      method: :delete,
      data: { confirm: "Are you sure?" } %>
      <%= link_to "Edit", edit_task_path(task) %>
      <%= link_to "Done?", done_task_path(task),
      method: :put %>
      </td>
  </tr>
  <% end %>
</table>

<%= link_to "Add a new task", new_task_path %>

app/views/tasks/new.html.erb
<h1>Tasks#new</h1>
<p>Find me in app/views/tasks/new.html.erb</p>

<%= render 'form' %>

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>
<p>Find me in app/views/tasks/show.html.erb</p>


<h2><%= @task.name %></h2>
<p><%= @task.content %></p>
<% if @task.done == true %>
<p>DONE!</p>
<% else %>
<p>TO DO!</p>
<% end %>
<p><%= @task.created_at %></p>

<%= link_to "Tasks list", tasks_path %>